/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProRouteImport } from './routes/pro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DraftsNewRouteImport } from './routes/drafts.new'
import { Route as DraftsDraftIdRouteImport } from './routes/drafts.$draftId'

const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsNewRoute = DraftsNewRouteImport.update({
  id: '/drafts/new',
  path: '/drafts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsDraftIdRoute = DraftsDraftIdRouteImport.update({
  id: '/drafts/$draftId',
  path: '/drafts/$draftId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pro': typeof ProRoute
  '/drafts/$draftId': typeof DraftsDraftIdRoute
  '/drafts/new': typeof DraftsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pro': typeof ProRoute
  '/drafts/$draftId': typeof DraftsDraftIdRoute
  '/drafts/new': typeof DraftsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pro': typeof ProRoute
  '/drafts/$draftId': typeof DraftsDraftIdRoute
  '/drafts/new': typeof DraftsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pro' | '/drafts/$draftId' | '/drafts/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pro' | '/drafts/$draftId' | '/drafts/new'
  id: '__root__' | '/' | '/pro' | '/drafts/$draftId' | '/drafts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProRoute: typeof ProRoute
  DraftsDraftIdRoute: typeof DraftsDraftIdRoute
  DraftsNewRoute: typeof DraftsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts/new': {
      id: '/drafts/new'
      path: '/drafts/new'
      fullPath: '/drafts/new'
      preLoaderRoute: typeof DraftsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts/$draftId': {
      id: '/drafts/$draftId'
      path: '/drafts/$draftId'
      fullPath: '/drafts/$draftId'
      preLoaderRoute: typeof DraftsDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProRoute: ProRoute,
  DraftsDraftIdRoute: DraftsDraftIdRoute,
  DraftsNewRoute: DraftsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
